# Generated by Django 3.2.9 on 2022-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
