# Generated by Django 3.2.9 on 2022-03-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_record_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='temperature',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
