# Generated by Django 3.2.9 on 2022-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_record_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='humidity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='pressure',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
